### ISSUE TITLE
CONFIGURATION_ROOT_DIR

### ISSUE THREAD

**Issue by wrxhardworking** [SalomePlatform/kernel#1]
```
SET(CONFIGURATION_ROOT_DIR $ENV{CONFIGURATION_ROOT_DIR} CACHE PATH "Path to the Salome CMake configuration files")
IF(EXISTS ${CONFIGURATION_ROOT_DIR})
  LIST(APPEND CMAKE_MODULE_PATH "${CONFIGURATION_ROOT_DIR}/cmake")
  INCLUDE(SalomeMacros NO_POLICY_SCOPE)
  message("include SalomeMAcros")
ELSE()
  MESSAGE(FATAL_ERROR "We absolutely need the Salome CMake configuration files, please define CONFIGURATION_ROOT_DIR !")
ENDIF()
```

**hey i am installing the salome-kenel module ,i meet some problem in cmake file :  what is the `CONFIGURATION_ROOT_DIR`? where is the `CONFIGURATION_ROOT_DIR`?**

**Comment by wrxhardworking** [comment]
hey thank y very much ,i will clone thih CONFIGURATION .did you open source it on GitHub recently? I couldn't find it on the official website before.

**Comment by mohd-afeef-badri** [comment]
@wrxhardworking  Yes, the SALOME platform's sources on GitHub are indeed recent. I am closing this issue since I see that the question has been answered by @nitawa.
