### ISSUE TITLE
The macro SIZEOF_INT must be defined.

### ISSUE THREAD

**Issue by wrxhardworking** [SalomePlatform/kernel#3]
```
/home/ethan/kernel/src/DSC/DSC_User/Datastream/Calcium/calciumf.c: In function ‘cplin_’:
/home/ethan/kernel/src/DSC/DSC_User/Datastream/Calcium/calciumf.c:174:2: error: #error "The macro SIZEOF_INT must be defined."
  174 | #error "The macro SIZEOF_INT must be defined."
      |  ^~~~~


```
i have construct the project,but when i use 'make' to complie, this erro happen ,should i modify the source code?

**Comment by wrxhardworking** [comment]
i have solve this problem , through define  macro by myselef

**Comment by Iceman9** [comment]
OmniORB versions >= 4.3.0 redefines **SIZEOF_*** macros as **OMNI_SIZEOF_***.

More specifically in **src/DSC/DSC_User/Datastream/Calcium/calciumf.c** replace all instances of **SIZEOF_*** with **OMNI_SIZEOF_*** if you want to fix it manually.

**Comment by wrxhardworking** [comment]
NO it's 20,24

**Comment by wrxhardworking** [comment]
> OmniORB 版本 >= 4.3.0 将 **SIZEOF_*** 宏重新定义为 **OMNI_SIZEOF_***。
> 
> 更具体地说，在 **src/DSC/DSC_User/Datastream/Calcium/calciumf.c** 中，如果要手动修复 **SIZEOF_***，请将其替换为 **OMNI_SIZEOF_***。

yes

**Comment by wrxhardworking** [comment]
> KERNEL 需要几个先决条件，其中包括 omniORB.请使用 [SAT，](https://github.com/SalomePlatform/.github/wiki/SAT)这将简化操作或确保您在公开 omniORB 的情况下进行编译。


today i use the SAT on windows, when i run  the sat by python ,no one log , i don't know  whether it is normal.

**Comment by huguesdpdn-aerospace** [comment]
Hello @wrxhardworking + @nitawa + @Iceman9 , please notice that I did a PR to fix that.

Please visit and review https://github.com/SalomePlatform/kernel/pull/5 - Thank you
